promo_memcache_default:
    path:     /
    defaults: { _controller: PromoMemcacheBundle:Default:index }
promo_memcache_default_test:
    path:     /test
    defaults: { _controller: PromoMemcacheBundle:Default:test }
