PromoMemcacheBundleDefault:
    path:     /
    defaults: { _controller: PromoMemcacheBundle:Default:index }
PromoMemcacheBundleDefaultTest:
    path:     /test
    defaults: { _controller: PromoMemcacheBundle:Default:test }
