promo_angular:
    resource: "@PromoAngularBundle/Resources/config/routing.yml"
    prefix:   /angular
promo_cassandra:
    resource: "@PromoCassandraBundle/Resources/config/routing.yml"
    prefix:   /cassandra
promo_photon:
    resource: "@PromoPhotonBundle/Resources/config/routing.yml"
    prefix:   /photon
promo_redis:
    resource: "@PromoRedisBundle/Resources/config/routing.yml"
    prefix: /redis
promo_memcache:
    resource: "@PromoMemcacheBundle/Resources/config/routing.yml"
    prefix: /memcache
nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
fos_js_routing_js:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"