services:
    promo_main.menu:
        class: Promo\MainBundle\Service\MenuService
        arguments: ["@service_container"]
        scope: "request"
    request:
        class: Promo\MainBundle\Service\RequestService
        arguments: ["@request_stack"]
