services:
#    promo_cassandra.example:
#        class: Promo\CassandraBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    promo_cassandra.cassandra:
        class: Promo\CassandraBundle\Cassanra
